name: CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                node-version: [10.x, 12.x]
                os: [ubuntu-latest, windows-latest]
            fail-fast: false

        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Test
              run: yarn test
